import type { ChampionAlert, OneChildEntry, TriageLabel } from '../types/survey'
import type { SynodalMark } from '../types/synodal'
import { storage } from './storage'

/**
 * Champion alert queue (PASTORAL_PULSE_SPEC § 4.2). Alerts are generated by:
 * - a `triggersChampion` question receiving a non-empty free-text response,
 * - the safeguarding ("Tell a leader") sheet,
 * - a pupil handle appearing from 2+ distinct staff within 5 calendar days,
 * - free-text triaged as concerned/alarmed (§ 4.3), whatever the question.
 */
const ALERTS_KEY = 'championAlerts'
const ONE_CHILD_KEY = 'oneChildEntries'
export const SCHOOL_ID = 'tt-pos-stjoseph-rc'

const DAY_MS = 86_400_000

export function listAlerts(): ChampionAlert[] {
  return storage.get<ChampionAlert[]>(ALERTS_KEY, [])
}

export function queueAlert(input: {
  triggerType: ChampionAlert['triggerType']
  context: string
  marks: SynodalMark[]
  pupilHandle?: string
  now?: Date
}): ChampionAlert {
  const now = input.now ?? new Date()
  const alert: ChampionAlert = {
    id: `alert-${now.getTime()}-${Math.random().toString(36).slice(2, 8)}`,
    schoolId: SCHOOL_ID,
    triggeredAt: now.toISOString(),
    triggerType: input.triggerType,
    pupilHandle: input.pupilHandle,
    context: input.context.slice(0, 500),
    marks: input.marks,
    status: 'open',
    readByDeadline: new Date(now.getTime() + 24 * 3_600_000).toISOString(),
  }
  storage.set(ALERTS_KEY, [alert, ...listAlerts()])
  return alert
}

export function shouldTriageAlert(label: TriageLabel): boolean {
  return label === 'concerned' || label === 'alarmed'
}

export function listOneChildEntries(): OneChildEntry[] {
  return storage.get<OneChildEntry[]>(ONE_CHILD_KEY, [])
}

export function addOneChildEntry(entry: OneChildEntry): void {
  const all = [entry, ...listOneChildEntries()]
  storage.set(ONE_CHILD_KEY, all)
  maybeQueuePatternAlert(entry.pupilHandle, all)
}

/** § 4.2: same handle from 2+ distinct staff within 5 calendar days → pattern alert. */
function maybeQueuePatternAlert(handle: string, entries: OneChildEntry[], now: Date = new Date()): void {
  const recent = entries.filter(
    (e) => e.pupilHandle === handle && now.getTime() - Date.parse(e.submittedAt) <= 5 * DAY_MS
  )
  const staff = new Set(recent.map((e) => e.submittedBy))
  if (staff.size < 2) return
  const alreadyOpen = listAlerts().some(
    (a) => a.triggerType === 'pattern' && a.pupilHandle === handle && a.status === 'open'
  )
  if (alreadyOpen) return
  queueAlert({
    triggerType: 'pattern',
    pupilHandle: handle,
    context: `${handle} noted by ${staff.size} staff within 5 days.`,
    marks: ['D'],
    now,
  })
}

export interface WatchlistRow {
  pupilHandle: string
  mentions: number
  days: number
  staff: number
  pattern: string
  marks: SynodalMark[]
}

/** § 3.4: pupils appearing in 2+ pulses across 3+ days in the past two weeks. */
export function watchlist(entries: OneChildEntry[] = listOneChildEntries(), now: Date = new Date()): WatchlistRow[] {
  const twoWeeks = 14 * DAY_MS
  const recent = entries.filter((e) => now.getTime() - Date.parse(e.submittedAt) <= twoWeeks)
  const byHandle = new Map<string, OneChildEntry[]>()
  for (const e of recent) {
    byHandle.set(e.pupilHandle, [...(byHandle.get(e.pupilHandle) ?? []), e])
  }
  const rows: WatchlistRow[] = []
  for (const [handle, list] of byHandle) {
    const days = new Set(list.map((e) => e.submittedAt.slice(0, 10)))
    if (list.length >= 2 && days.size >= 3) {
      rows.push({
        pupilHandle: handle,
        mentions: list.length,
        days: days.size,
        staff: new Set(list.map((e) => e.submittedBy)).size,
        pattern: list
          .map((e) => e.notedFor)
          .filter(Boolean)
          .join(' · '),
        marks: ['D'],
      })
    }
  }
  return rows.sort((a, b) => b.mentions - a.mentions)
}

/** Heuristic from spec § 3.2 — reject anything that looks like a real name. */
export function looksLikeRealName(s: string): boolean {
  return /^[A-Z][a-z]{2,}(\s[A-Z][a-z]{2,})?$/.test(s.trim())
}
