import type { ChampionAlert, ChampionOutcome, OneChildEntry, TriageLabel, WatchlistAction } from '../types/survey'
import type { SynodalMark } from '../types/synodal'
import { storage } from './storage'

/**
 * Champion alert queue (PASTORAL_PULSE_SPEC § 4.2). Alerts are generated by:
 * - a `triggersChampion` question receiving a non-empty free-text response,
 * - the safeguarding ("Tell a leader") sheet,
 * - a pupil handle appearing from 2+ distinct staff within 5 calendar days,
 * - free-text triaged as concerned/alarmed (§ 4.3), whatever the question.
 */
const ALERTS_KEY = 'championAlerts'
const ONE_CHILD_KEY = 'oneChildEntries'
const WATCHLIST_ACTIONS_KEY = 'watchlistActions'
export const SCHOOL_ID = 'tt-pos-stjoseph-rc'

const DAY_MS = 86_400_000
const HOUR_MS = 3_600_000

/**
 * DEMO SEED — a small realistic queue so the Champion workspace is
 * demonstrable before local activity accumulates. Real deployments start
 * from the server-side queue; these seeds live only in the local store.
 */
function seedAlerts(now: Date = new Date()): ChampionAlert[] {
  const at = (hoursAgo: number) => new Date(now.getTime() - hoursAgo * HOUR_MS)
  const mk = (id: string, hoursAgo: number, partial: Partial<ChampionAlert>): ChampionAlert => ({
    id,
    schoolId: SCHOOL_ID,
    triggeredAt: at(hoursAgo).toISOString(),
    triggerType: 'free_text',
    context: '',
    marks: ['L'],
    status: 'open',
    readByDeadline: new Date(at(hoursAgo).getTime() + 24 * HOUR_MS).toISOString(),
    ...partial,
  })
  return [
    mk('seed-alert-pattern', 20, {
      triggerType: 'pattern',
      pupilHandle: 'F2-073',
      context: 'F2-073 noted by 3 staff across 4 days.',
      marks: ['D'],
    }),
    mk('seed-alert-freetext', 6, {
      triggerType: 'free_text',
      context: 'A pupil in my form seems withdrawn since Monday and skipped lunch twice this week.',
      marks: ['L', 'D'],
    }),
    mk('seed-alert-reviewed', 30, {
      triggerType: 'safeguarding',
      context: 'Please keep an eye on the back corridor at first break.',
      status: 'reviewed',
      championReadBy: 'champion-demo',
    }),
  ]
}

function seedOneChild(now: Date = new Date()): OneChildEntry[] {
  const entry = (staff: string, daysAgo: number, notedFor: string): OneChildEntry => ({
    pupilHandle: 'F2-073',
    yearGroup: 'F2',
    notedFor,
    submittedBy: staff,
    submittedAt: new Date(now.getTime() - daysAgo * DAY_MS).toISOString(),
  })
  return [
    entry('teacher-mp', 1, 'quiet all day, sat alone at lunch'),
    entry('teacher-rk', 2, 'homework missing again, seemed tired'),
    entry('teacher-sd', 4, 'flinched when asked about home'),
  ]
}

export function listAlerts(): ChampionAlert[] {
  return storage.get<ChampionAlert[]>(ALERTS_KEY, seedAlerts())
}

/** Inbox order: open first by SLA remaining (soonest deadline first), then closed by recency. */
export function triagedAlerts(now: Date = new Date()): ChampionAlert[] {
  void now
  const open = listAlerts().filter((a) => a.status === 'open')
  const closed = listAlerts().filter((a) => a.status !== 'open')
  open.sort((a, b) => Date.parse(a.readByDeadline) - Date.parse(b.readByDeadline))
  closed.sort((a, b) => Date.parse(b.triggeredAt) - Date.parse(a.triggeredAt))
  return [...open, ...closed]
}

export function acknowledgeAlert(id: string, championId: string): void {
  storage.set(
    ALERTS_KEY,
    listAlerts().map((a) => (a.id === id && a.status === 'open' ? { ...a, status: 'reviewed' as const, championReadBy: championId } : a))
  )
}

/**
 * Closing an alert requires a structured outcome (council protocol Seat 4.2).
 * The outcome note stays in the Champion workspace — it is never included in
 * any export, digest or rollup. Throws if the note is missing.
 */
export function closeAlert(id: string, championId: string, outcome: ChampionOutcome, note: string): void {
  if (!note.trim()) throw new Error('An outcome note is required to close an alert')
  storage.set(
    ALERTS_KEY,
    listAlerts().map((a) =>
      a.id === id
        ? {
            ...a,
            status: 'actioned' as const,
            championReadBy: a.championReadBy ?? championId,
            outcome,
            outcomeNote: note.trim(),
            closedAt: new Date().toISOString(),
          }
        : a
    )
  )
}

/** Hours until (positive) or past (negative) the 24h read deadline. */
export function slaHoursRemaining(alert: ChampionAlert, now: Date = new Date()): number {
  return (Date.parse(alert.readByDeadline) - now.getTime()) / HOUR_MS
}

export function watchlistActions(): Record<string, WatchlistAction> {
  return storage.get<Record<string, WatchlistAction>>(WATCHLIST_ACTIONS_KEY, {})
}

export function setWatchlistAction(pupilHandle: string, action: WatchlistAction): void {
  storage.set(WATCHLIST_ACTIONS_KEY, { ...watchlistActions(), [pupilHandle]: action })
}

export function queueAlert(input: {
  triggerType: ChampionAlert['triggerType']
  context: string
  marks: SynodalMark[]
  pupilHandle?: string
  now?: Date
}): ChampionAlert {
  const now = input.now ?? new Date()
  const alert: ChampionAlert = {
    id: `alert-${now.getTime()}-${Math.random().toString(36).slice(2, 8)}`,
    schoolId: SCHOOL_ID,
    triggeredAt: now.toISOString(),
    triggerType: input.triggerType,
    pupilHandle: input.pupilHandle,
    context: input.context.slice(0, 500),
    marks: input.marks,
    status: 'open',
    readByDeadline: new Date(now.getTime() + 24 * 3_600_000).toISOString(),
  }
  storage.set(ALERTS_KEY, [alert, ...listAlerts()])
  return alert
}

export function shouldTriageAlert(label: TriageLabel): boolean {
  return label === 'concerned' || label === 'alarmed'
}

export function listOneChildEntries(): OneChildEntry[] {
  return storage.get<OneChildEntry[]>(ONE_CHILD_KEY, seedOneChild())
}

export function addOneChildEntry(entry: OneChildEntry): void {
  const all = [entry, ...listOneChildEntries()]
  storage.set(ONE_CHILD_KEY, all)
  maybeQueuePatternAlert(entry.pupilHandle, all)
}

/** § 4.2: same handle from 2+ distinct staff within 5 calendar days → pattern alert. */
function maybeQueuePatternAlert(handle: string, entries: OneChildEntry[], now: Date = new Date()): void {
  const recent = entries.filter(
    (e) => e.pupilHandle === handle && now.getTime() - Date.parse(e.submittedAt) <= 5 * DAY_MS
  )
  const staff = new Set(recent.map((e) => e.submittedBy))
  if (staff.size < 2) return
  const alreadyOpen = listAlerts().some(
    (a) => a.triggerType === 'pattern' && a.pupilHandle === handle && a.status === 'open'
  )
  if (alreadyOpen) return
  queueAlert({
    triggerType: 'pattern',
    pupilHandle: handle,
    context: `${handle} noted by ${staff.size} staff within 5 days.`,
    marks: ['D'],
    now,
  })
}

export interface WatchlistRow {
  pupilHandle: string
  mentions: number
  days: number
  staff: number
  pattern: string
  marks: SynodalMark[]
}

/** § 3.4: pupils appearing in 2+ pulses across 3+ days in the past two weeks. */
export function watchlist(entries: OneChildEntry[] = listOneChildEntries(), now: Date = new Date()): WatchlistRow[] {
  const twoWeeks = 14 * DAY_MS
  const recent = entries.filter((e) => now.getTime() - Date.parse(e.submittedAt) <= twoWeeks)
  const byHandle = new Map<string, OneChildEntry[]>()
  for (const e of recent) {
    byHandle.set(e.pupilHandle, [...(byHandle.get(e.pupilHandle) ?? []), e])
  }
  const rows: WatchlistRow[] = []
  for (const [handle, list] of byHandle) {
    const days = new Set(list.map((e) => e.submittedAt.slice(0, 10)))
    if (list.length >= 2 && days.size >= 3) {
      rows.push({
        pupilHandle: handle,
        mentions: list.length,
        days: days.size,
        staff: new Set(list.map((e) => e.submittedBy)).size,
        pattern: list
          .map((e) => e.notedFor)
          .filter(Boolean)
          .join(' · '),
        marks: ['D'],
      })
    }
  }
  return rows.sort((a, b) => b.mentions - a.mentions)
}

/** Heuristic from spec § 3.2 — reject anything that looks like a real name. */
export function looksLikeRealName(s: string): boolean {
  return /^[A-Z][a-z]{2,}(\s[A-Z][a-z]{2,})?$/.test(s.trim())
}
